services:
#    dc_home.example:
#        class: DC\HomeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
 dc_generation:
        class: DC\HomeBundle\Generation\DCGeneration
 dc_messages:
        class: DC\HomeBundle\SendMessages\SendMessages
