<?php

namespace DC\AdminBundle\Repository;

use DC\AdminBundle\Entity\Booking;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{


    public function getBooking($id){

        $qb = $this->createQueryBuilder('a');


        $qb
            ->where('a.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function getBookingsByDryCleaner($idDC,$opt){

        $qb = $this->createQueryBuilder('a');


        $qb
            ->where('a.drycleaner = :id')
            ->setParameter('id', $idDC)
        ;
        if($opt !== null) {
            $qb
                ->andWhere('a.booked = :booked')
                ->setParameter('booked', $opt);
        }


        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function updateSlotBooking($booking,$id){
        $qb = $this->createQueryBuilder('DCAdminBundle:Booking');

     $q=   $qb
            ->update('DCAdminBundle:Booking a')
            ->set('a.drycleanerId',$qb->expr()->literal($booking->getDrycleanerId()))
            ->set('a.washingmachineId',$qb->expr()->literal($booking->getWashingmachineId()))
            ->set('a.booked',1)
            ->where('a.id = :id')
            ->setParameter('id',$id)
            ->getQuery();

        $sql=$q->getSQL();


        $p = $q->execute();


    }


}