<?php

namespace DC\AdminBundle\Repository;

/**
 * OpeningHoursDCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHoursDCRepository extends \Doctrine\ORM\EntityRepository
{
}
