<?php

namespace DC\AdminBundle\Repository;

/**
 * OpeningHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpeningHoursRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOpeningHoursByDryCleaner($idDC){

        $qb = $this->createQueryBuilder('a');


        $qb
            ->where('a.idDC = :idDC')
            ->setParameter('idDC', $idDC)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
