<?php

namespace DC\AdminBundle\Repository;

/**
 * WashingMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WashingMachineRepository extends \Doctrine\ORM\EntityRepository
{


    public function myFindAllByWashingMachinesByDryCleaner($id){

        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.idDrycleaner = :id')
            ->setParameter('id', $id);
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;

    }

    public function countWashingMachinesByDryCleaner($id,$state){

        $qb = $this->createQueryBuilder('a');
        $qb
            ->select('count(a.id)')
            ->where('a.idDrycleaner = :id')
            ->setParameter('id', $id)
            ->andWhere('a.avaibility = :avaibility')
            ->setParameter('avaibility',$state)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function getLastWM($id,$state){
        $qb = $this->createQueryBuilder('a');
        $qb
            ->select('a.id')
            ->where('a.idDrycleaner = :id')
            ->setParameter('id', $id)
            ->andWhere('a.avaibility = :avaibility')
            ->setParameter('avaibility',$state)
            ->setMaxResults(1)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function changeAvaibility($id,$state){
        $qb = $this->createQueryBuilder('DCAdminBundle:WashingMachine');

      $q =  $qb
            ->update('DCAdminBundle:WashingMachine a')
            ->set('a.avaibility',$qb->expr()->literal($state))
            ->where('a.id = :id')
            ->setParameter('id',$id)
            ->getQuery();

       
        $p = $q->execute();
    }
   
}
